name: Godot CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
         operating-system: [ubuntu-20.04, ubuntu-20.04]
    env: 
      GODOT_PATH: Godot/godot
    steps:
      - uses: actions/checkout@v1
      - name: Install
        run: |
            sudo apt install unzip wget
            cd .. && mkdir Godot && cd Godot
            wget https://downloads.tuxfamily.org/godotengine/3.3.2/Godot_v3.3.2-stable_linux_headless.64.zip
            unzip Godot_v3.3.2-stable_linux_headless.64.zip
            mv Godot_v3.3.2-stable_linux_headless.64 godot
      - name: Export templates
        run: |
            mkdir -p $HOME/.local/share/godot/templates/3.3.2.stable/
            cd $HOME/.local/share/godot/templates/3.3.2.stable/
            wget https://downloads.tuxfamily.org/godotengine/3.3.2/Godot_v3.3.2-stable_export_templates.tpz
            unzip Godot_v3.3.2-stable_export_templates.tpz
            mv templates/* .
      - name: Export
        run: |
            cd simu
            ../../$GODOT_PATH --export "Linux/X11" simulation.pck
            ls
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Run
        run: |
            cd ..
            python3 -m unittest gobot-sim.tests.connection_tests
            python3 -m unittest gobot-sim.tests.state_tests
            python3 -m unittest gobot-sim.tests.navigation_tests
            python3 -m unittest gobot-sim.tests.rotation_tests
            python3 -m unittest gobot-sim.tests.manipulation_tests
            python3 -m unittest gobot-sim.tests.process_test
            python3 -m unittest gobot-sim.tests.other_tests
            python3 -m unittest gobot-sim.tests.demonstration

